== Podman CLI

The first thing we’ll work with is the podman CLI. If you are familiar
with containers on docker, you’ll find a lot of the work here to be
almost identical to the command-line you’re used to on docker. This is
on purpose. Podman has a docker compatible command set, it also runs the
same Open Container Initiative (OCI) compliant images that you may be
used to running on docker.

Throughout this lab we’ll be using container images, in fact, that came
right from docker hub, but we’ll also see container images from other
sources.

== Verifying that podman is installed

First, let’s see what version of podman we’re working with.

[source,bash,subs="+macros,+attributes",role=copy]
----
podman --version
----

This should return something like this:

Let’s also look to see what images are available to us locally

[source,bash,subs="+macros,+attributes",role=copy]
----
podman image list
----

== Look for running containers

Now let’s see if there are any containers running

[source,bash,subs="+macros,+attributes",role=copy]
----
podman ps
----

You should see a container running named default-httpd

== Stopping, starting, and removing containers

To stop a container, you use the `+podman stop [identifier]+` command.
The `+identifier+` can be either the container’s name, or ID. Let’s stop
default-httpd by its name.

[source,bash,subs="+macros,+attributes",role=copy]
----
podman stop default-httpd
----

Podman confirms this action only by returning the container’s ID or Name
(depending on the podman version) that you stopped. Now, `+podman ps+`
will show no running containers, but the container isn’t gone, you can
see all containers, using the `+podman ps -a+` command. Let’s try that.

[source,bash,subs="+macros,+attributes",role=copy]
----
podman ps -a
----

You should see a list of all containers, including those that are
stopped, along with their state.

We can start the container again with `+podman start [identifier]+`,
again the identifier can be the container ID, or it’s name.

[source,bash,subs="+macros,+attributes",role=copy]
----
podman start default-httpd
----

Just like when we stopped it, podman should only return the containers
Name, or ID, if it succeeded.

Now, what about deleting containers? You can use
`+podman rm [identifier]+` to remove a container.

First let’s stop that running container, then we’ll remove it.https://docs.google.com/document/d/15WowVUGY4xSKMdg6fCXrpIAMXlUxkLjJixYcqXbJDgg/edit?tab=t.0

[source,bash,subs="+macros,+attributes",role=copy]
----
podman stop default-httpd && podman rm default-httpd
----

You should get the identifier back twice, because we performed two
actions on the same container. Now a `+podman ps -a+` should return no
containers.

[source,bash,subs="+macros,+attributes",role=copy]
----
podman ps -a
----

== Working with Images

What if we need a new image from our container registry? A container
registry is sort of like a package repository, or even a code
repository. It’s a central place where our container images live. Those
images will usually have different builds, or versions associated with
them, separated by Tags. By default podman will pull the `+latest+` tag.
Let’s try to pull a specific build of the mariadb image, from the Docker
Hub public registry.

[source,bash,subs="+macros,+attributes",role=copy]
----
podman pull docker.io/mariadb:lts-ubi9
----

You’ll see an output similar to this:

Much like parfait, images have layers. These multiple lines of "`copying
blob…`" are the various layers of this container image being downloaded
and built into the container image. And everybody loves parfait.

Now, you’ll find the `+mariadb:lts-ubi9+` image in your local list of
container images.

A note on tags. in this example, we downloaded the mariadb build based
on the RHEL 9 Universal Base Image. This is denoted by the tag
`+lts-ubi9+`. If you left off the tag, podman would have defaulted to
downloading `+mariadb:latest+` which in this case is a container built
on an entirely different base. Containers give us this sort of
flexibility.

[source,bash,subs="+macros,+attributes",role=copy]
----
podman image list
----

Now, we don’t actually need that mariadb container, but it would be
useful for you to know how to delete a container image. Let’s delete
`+mariadb:lts-ubi9+`

[source,bash,subs="+macros,+attributes",role=copy]
----
podman rmi docker.io/mariadb:lts-ubi9
----

And you’ll get the following output:

What’s that Untagged line all bout? Podman maintains tags for every
image locally, this is used for more advanced podman work than we’ll
approach in this lab. But this is how you tell podman where to `+push+`
an image if you were to make changes to it (assuming you have the
permission to push a container to that registry).

Now, in the next step we’ll learn how to run a new container in podman!
